name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install package with dev dependencies
        run: pip install -e ".[dev]"

#      - name: Run ruff check
#        run: ruff check --output-format=github --no-fix terratorch/ --exclude terratorch/vllm/
      - name: Run ruff format check
        run: ruff format --check --diff terratorch/ --exclude terratorch/vllm/
